export const data = [
  {
    'name': "Inmobiliaria Sol Naciente",
    'client': "Jacob Roberts",
    'email_client': "jacobroberts@me.com",
    'description': "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries.",
    'date_in': "2022-01-01",
    'date_out': "2022-01-31",
    'status': "Pendiente",
  },
  {
    'name': "E-Commerce Supermercado Casa Blanca",
    'client': "Fernando Torres",
    'email_client': "fernando@me.com",
    "description": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    'date_in': "2022-02-01",
    'date_out': "2022-02-28",
    'status': "Pendiente",
  },
  {
    'name': "Bot Telegram",
    'client': "Camilo Salazar",
    'email_client': "camilo@me.com",
    "description": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    'date_in': "2022-03-01",
    'date_out': "2022-03-31",
    'status': "Pendiente",
  },
  {
    'name': "Crear sitio web joyeria",
    'client': "Oscar Hernandez",
    'email_client': "oscar@me.com",
    "description": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    'date_in': "2022-04-01",
    'date_out': "2022-04-30",
    'status': "Completo",
  },  
  {
    'name': "Crear sitio web tienda de ropa",
    'client': "Yohana Perez",
    'email_client': "yohana@me.com",
    "description": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    'date_in': "2022-05-01",
    'date_out': "2022-05-31",
    'status': "Completo",
  },  
] 